### ISSUE TITLE
Conflicts with plugin Hirak/prestissimo

### ISSUE THREAD

**Issue by philiprabbett** [ffraenz/private-composer-installer#1]
> When using this plugin in conjunction with hirak/prestissimo, the download of acf-pro fails because the custom RemoteFileSystem is overwritten. In order to get it working, we should ensure that this plugins runs after hirak/prestissimo.
As both are running with a priority set to 0, setting this one to -1 resolves the issue.
>- Mickaël PERRIN

See this patch for similar fix: https://github.com/PhilippBaschke/acf-pro-installer/pull/20

`PluginEvents::PRE_FILE_DOWNLOAD => [ 'injectPlaceholders', -1 ],`

**Comment by ffraenz** [comment]
Hi @philiprabbett, thank you for reporting this issue. I applied a fix similar to https://github.com/PhilippBaschke/acf-pro-installer/pull/20. Would you report back if this fixes the compatibility issues with [hirak/prestissimo](https://github.com/hirak/prestissimo)?

**Comment by philiprabbett** [comment]
That works for me, no problems since! Thanks for that.
