### ISSUE TITLE
Fatal Error with `composer install` and PHP 7

### ISSUE THREAD

**Issue by pierrotevrard-idp** [ffraenz/private-composer-installer#14]
This error occurs when running command `composer install`

> Fatal error: Uncaught TypeError: Argument 1 passed to FFraenz\PrivateComposerInstaller\Plugin::getUrlPlaceholders() must be of the type string, null given

Please, cast the value as a string or allow null

**Comment by ffraenz** [comment]
Hi! Thank you for your report and pull request. I am wondering why package dist URLs being NULL is not documented in the composer package. Nevertheless packages without a dist URL now get ignored by this composer installer instead of raising an exception. I publish new releases shortly.

**Comment by pierrotevrard-idp** [comment]
Me neither... 

A strange behavior, but probably expected.

I get Composer 1.9.0, PHP 7.1.32 and a WordPress 5.2.4 instance built with the `johnpbloch/wordpress` package.

Whatever, you're doing a good job, thank you
