### ISSUE TITLE
PhpOption\Option not found

### ISSUE THREAD

**Issue by dashifen-gu** [ffraenz/private-composer-installer#16]
I'm running into the following error when trying to set this up for a new project: `

```
PHP Fatal error:  Uncaught Error: Class 'PhpOption\Option' not found in \docroot\wp-content\vendor\vlucas\phpdotenv\src\Environment\Adapter\PutenvAdapter.php:28
Stack trace:
#0 \docroot\wp-content\vendor\ffraenz\private-composer-installer\src\PrivateComposerInstaller\Env.php(69): Dotenv\Environment\Adapter\PutenvAdapter->get('ACF_PRO_KEY')
#1 \docroot\wp-content\vendor\ffraenz\private-composer-installer\src\PrivateComposerInstaller\Plugin.php(103): FFraenz\PrivateComposerInstaller\Env->get('ACF_PRO_KEY')
#2 [internal function]: FFraenz\PrivateComposerInstaller\Plugin->injectPlaceholders(Object(Composer\Plugin\PreFileDownloadEvent))
#3 composer.phar/src/Composer/EventDispatcher/EventDispatcher.php(176): call_user_func(Array, Object(Composer\Plugin\PreFileDownloadEvent))
```

Here's the relevant `composer.json` portion:

```
{
  "type": "package",
  "package": {
    "name": "advanced-custom-fields/advanced-custom-fields-pro",
    "version": "5.8.7",
    "type": "wordpress-plugin",
    "dist": {
      "type": "zip",
      "url": "https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k={%ACF_PRO_KEY}&t={%VERSION}"
    },
    "require": {
      "composer/installers": "^1.4",
      "ffraenz/private-composer-installer": "^3.0"
    }
  }
}
```

I've also tried `"ffraenz/private-composer-installer": "^2.0"` which is working in a different project, so I'm not sure why that error's popping up for this build.  Thoughts?

**Comment by ffraenz** [comment]
The error is triggered inside the `vlucas/phpdotenv` dependency of this project. The `phpoption/phpoption` package seems to be missing for it to run properly. I'm not sure why composer would not install it automatically.

I would delete the vendor folder and regenerate all packages. If the outcome is the same, I would also regenerate the `composer.lock` file. Your `composer.json` snippet looks fine to me.

**Comment by dashifen-gu** [comment]
Yeah, I've done all that.  I spent about three hours trying to figure out why this was happening -- especially since using your tool on other projects has worked perfectly.  I even cloned one of those projects and did a `composer install` on it just to see if it was something about composer on this machine was causing a problem and the other one worked fine.  I may have to take other dependencies out and see if it's a conflict between ACF's install and one of the other ones.  I'll close the ticket since this seems like something unrelated to this repo.  Happy new year!

**Comment by ffraenz** [comment]
You too, happy new year! I'm sorry to hear that. Is the `phpoption/phpoption` package present in the vendors folder after running `composer install`? Does it appear inside `composer.lock`?

**Comment by dashifen-gu** [comment]
It isn't.  In fact, the entire vendor folder is empty despite seeing lines like this:

```
  - Installing composer/installers (v1.7.0): Loading from cache
  - Installing symfony/polyfill-ctype (v1.13.1): Loading from cache
  - Installing phpoption/phpoption (1.7.2): Loading from cache
  - Installing vlucas/phpdotenv (v3.6.0): Loading from cache
  - Installing ffraenz/private-composer-installer (v3.0.1): Loading from cache
```

Something seems like it's deleting the vendor folder in the middle of the process.  This seems like something I can dig into.  Thanks!

**Comment by ffraenz** [comment]
When you put the vendor folder inside the WordPress structure the installation of WordPress itself may overwrite the vendor folder depending on the order composer is installing packages. Issue #6 is related to that. In my projects I keep the vendor folder completely separated from the WordPress instance.

**Comment by dashifen-gu** [comment]
Yup, I suspect that's what's going on.  I'll debug it later.  Thanks for pointing me in the right direction!
