### ISSUE TITLE
wpml

### ISSUE THREAD

**Issue by jnz31** [ffraenz/private-composer-installer#18]
i found you mention the option to install wpml as well, but i'm not sure what i am doing wrong here (the name attribute is a guessing by me, not sure if it is correct or if it needs to be something else..?, the url  and parameters i grabbed from my wpml account):

```
    {
      "type": "package",
      "package": {
        "name": "wpml/sitepress-multilingual-cms",
        "version": "4.3.11",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://wpml.org/?download={%PLUGIN_WPML_DOWNLOAD}&user_id={%PLUGIN_WPML_USER_ID}&subscription_key={%PLUGIN_WPML_SUBSCRIPTION_KEY}&t=1585915805&version={%VERSION}"
        },
        "require": {
          "ffraenz/private-composer-installer": "^4.0"
        }
      }
    }
```

and in my .env file i replace the variables via
```
PLUGIN_WPML_DOWNLOAD=xxx
PLUGIN_WPML_USER_ID=yyy
PLUGIN_WPML_SUBSCRIPTION_KEY=zzz
```

plus how would you go on and install the other wpml plugins, like string-translation etc..?
can you help?

**Comment by ffraenz** [comment]
Indeed, in [older versions of the README](https://github.com/ffraenz/private-composer-installer/blob/8b3092077fd72447cd15fe4b37a55a8db5b77333/README.md#wordpress-wpml-plugin) I mentioned how to install WPML packages with private-composer-installer. I don't know if this does still applies or if WPML changed something on their end.

You didn't specify the exact problem you encountered? What did go wrong?

**Comment by jnz31** [comment]
thanks @ffraenz for the headsup. i gave it another shot and and realized, i made an error. i expected composer to install the missing plugin on `composer update`, whilst i forgot about the `composer require xyz` call. 
not sure why, but it terminal (zsh) was throwing error, when also submitting the version (*).
i had to wrap it in quotes, to make it work:
zsh: no matches found: wpml/wpml-multilingual-cms:*
`composer require wpml/wpml-multilingual-cms:"*"` works fine
