### ISSUE TITLE
Drop-in replacement for acf-pro-installer?

### ISSUE THREAD

**Issue by strarsis** [ffraenz/private-composer-installer#2]
It seems that this private composer installer can also 
be used as a drop-in replacement for [acf-pro-installer](https://github.com/PhilippBaschke/acf-pro-installer)? 

This would be nice because then I can use [hirak/prestissimo](https://github.com/hirak/prestissimo) again, 
current `composer update` times are very long.

**Comment by philiprabbett** [comment]
100% a replacement for acf-pro-installer and best of all, it works for other paid plugins too.
