### ISSUE TITLE
Incompatile with prestissimo plugin

### ISSUE THREAD

**Issue by szepeviktor** [ffraenz/private-composer-installer#21]
I think it tries to download from the stored URL.

```
    62/67:      https://codeload.github.com/symfony/polyfill-ctype/legacy.zip/550ebaac289296ce228a706d0867afc34687e3f4
    0: :        https://connect.advancedcustomfields.com/index.php
    63/67:      https://codeload.github.com/squizlabs/PHP_CodeSniffer/legacy.zip/65b12cdeaaa6cd276d4c3033a95b9b88b12701e7
```

https://github.com/hirak/prestissimo

May be related to https://github.com/hirak/prestissimo/issues/219

Please advise.

**Comment by ffraenz** [comment]
Please provide your `composer.json` or a similar test case to reproduce the bug. What do you mean by 'the stored URL'?

**Comment by szepeviktor** [comment]
1. `composer global require hirak/prestissimo`
1. Set up private-composer-installer with e.g. ACF Pro
1. run `composer update`
1. See the output above: prestissimo fails to preload ACF Pro, it keeps trying for a while...

**Comment by szepeviktor** [comment]
> What do you mean by 'the stored URL'?

the one without secrets, with placeholders

**Comment by szepeviktor** [comment]
so actually prestissimo abuses the ACF download server...

**Comment by mcaskill** [comment]
@szepeviktor Are you using the correct URI and placeholders for `dist.url` as shown on the README?

```
https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k={%ACF_PRO_KEY}&t={%VERSION}
```

As for hirak/prestissimo#219, I believe that issue is with the fact that pivvenit/acf-composer-bridge does not use the ACF Pro license key anywhere in its source code.

**Comment by szepeviktor** [comment]
I think yes. It was long time ago.

```
"https://connect.advancedcustomfields.com/index.php?p=pro&a=download&t={%VERSION}&k={%ACF_PRO_KEY}"
```

**Comment by ffraenz** [comment]
@szepeviktor Is this still relevant or may I close this issue?

**Comment by szepeviktor** [comment]
Let's close it!
