### ISSUE TITLE
Support for Composer 2

### ISSUE THREAD

**Issue by mcaskill** [ffraenz/private-composer-installer#23]
Composer 2.0 is getting closer to a stable release and this plugin will need an update, as per: composer/composer#8726

Thanks

**Comment by strarsis** [comment]
@ffraenz: Could I install this plugin already to try composer 2 with an existing WordPress/Bedrock setup?

**Comment by mcaskill** [comment]
Resolved in [v5.0.0](https://github.com/ffraenz/private-composer-installer/releases/tag/v5.0.0)
