### ISSUE TITLE
Can you place the .env file in a directory above `composer.json`?

### ISSUE THREAD

**Issue by JodiWarren** [ffraenz/private-composer-installer#26]
We have a project where the `.env` file is placed in a directory above WordPress and `composer.json`. This is fine when accessing it normally, as you can specify a path. However, it's hard-coded in Private Composer Installer. We got around it for now by creating a second `.env` file within the WordPress folder, but it's not ideal. It appears to be hard coded at the moment, so I imagine this is actually a feature request.

**Comment by ffraenz** [comment]
Hi @JodiWarren, thank you for your use case description and proposal. I definitely want to offer a way to use non-default dotenv file names and/or locations. Searching the file tree up to the root for a `.env` file would work very well out of the box. Though, I also consider adding a property to the `extra` section of `composer.json` to explicitly point to a custom dotenv file location to solve the problem in a more general way. I'd like to tackle this problem in the upcoming major update #25.

**Comment by mcaskill** [comment]
Resolved in [v5.0.0](https://github.com/ffraenz/private-composer-installer/releases/tag/v5.0.0)

**Comment by ffraenz** [comment]
@JodiWarren Both locating `.env` files in parent directories by default as well as setting a custom file location and file name is now available. Please let me know if this works for you.
