### ISSUE TITLE
Update dependency vlucas/phpdotenv to v5

### ISSUE THREAD

**Issue by sandrodz** [ffraenz/private-composer-installer#29]
https://github.com/ffraenz/private-composer-installer/blob/master/composer.json#L24

<img width="1430" alt="Screen Shot 2020-09-23 at 14 57 17" src="https://user-images.githubusercontent.com/8479569/94004081-321aad00-fdad-11ea-99c0-cbb6fc182929.png">

**Comment by szepeviktor** [comment]
Docs: https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md#v4-to-v5

**Comment by mcaskill** [comment]
Resolved in [v5.0.0](https://github.com/ffraenz/private-composer-installer/releases/tag/v5.0.0)
