### ISSUE TITLE
Support for plugins on envato?

### ISSUE THREAD

**Issue by strarsis** [ffraenz/private-composer-installer#3]
Can this installer also be used for pulling + installing plugins bought on envato?

**Comment by ffraenz** [comment]
That depends on how Envato distributes the packages and how the content is structured. The package URL needs to be permanent and the ZIP file should contain the WordPress plugin files in the root folder to let WPackagist do its job.

Would you provide an example URL from Envato? (Replacing containing tokens and codes by placeholders, of course)

**Comment by strarsis** [comment]
All files & documentation:
````
https://codecanyon.net/user/<envato-user>/download_purchase/<purchase-code>
````

Installable WordPress files only:
````
https://codecanyon.net/user/<envato-user>/download_purchase/<purchase-code>?accessor=wordpress_plugin
````

License certificate & purchase code (PDF):
````
https://codecanyon.net/downloads/certificate/<purchase-code>.pdf
````

License certificate & purchase code (text):
````
https://codecanyon.net/downloads/certificate/<purchase-code>
````

**Comment by ffraenz** [comment]
For this installer to download the Envato WordPress plugin we only need the 'Installable WordPress files only' ZIP file. There is no version parameter in the URL structure you sent. This means that you can't control which version gets downloaded, you are getting the latest version only.

Add the following entry to the `repositories` field inside `composer.json` replacing `package-name` by the actual package name you want to install.

```json
{
  "type": "package",
  "package": {
    "name": "package-name/package-name",
    "version": "1.0.0",
    "type": "wordpress-plugin",
    "dist": {
      "type": "zip",
      "url": "https://codecanyon.net/user/{%PLUGIN_ENVATO_USER}/download_purchase/{%PLUGIN_ENVATO_PACKAGE_NAME}?accessor=wordpress_plugin"
    },
    "require": {
      "composer/installers": "^1.4",
      "ffraenz/private-composer-installer": "^1.0"
    }
  }
}
```

Provide the Envato user token and the package purchase token through e.g. the `.env` file.

```
PLUGIN_ENVATO_USER=xyz
PLUGIN_ENVATO_PACKAGE_NAME=abc
```

Let composer require the private package.

```
composer require package-name/package-name:*
```

You can name the environment variables as you please. Would you give me feedback on this? I'll add this example to the README if it works as expected.
