### ISSUE TITLE
Support for newer (v3) version of vlucas/phpdotenv

### ISSUE THREAD

**Issue by ihorvorotnov** [ffraenz/private-composer-installer#4]
The `vlucas/phpdotenv` package version 3 was released about a month ago and includes some great improvements. As this package is a must-have not only for `ffraenz/private-composer-installer` but for all kinds of projects, the chances that `^3.0` is already in the `composer.json` are quite high.

However, v3 comes with some breaking changes that you can check in [Upgrading Guide](https://github.com/vlucas/phpdotenv/blob/master/UPGRADING.md). I've done some tests and it seems changing `new Dotenv(getcwd())` to `Dotenv::create(getcwd())` is the only change needed.

PR is coming in a minute.

**Comment by ffraenz** [comment]
Thank you for your pull request. I reviewed your changes and merged them. Because updating `vlucas/phpdotenv` to version `^3.0` will result in conflicts in all existing projects depending on older versions `<3.0.0` I created a new major release `2.0.0` for this package. Does this work for you?

**Comment by ihorvorotnov** [comment]
@ffraenz Yes, that's the way to go I believe - legacy version that still supports v2 of `vlucas/phpdotenv` and a new, major version that supports v3. This way anyone can choose the version that fits their setup.

Thanks for the merge! 👍
