### ISSUE TITLE
Version constraint for Composer 1 does not allow ACF 5.10.x to update

### ISSUE THREAD

**Issue by srsimonson** [ffraenz/private-composer-installer#43]
This issue here:
https://github.com/PhilippBaschke/acf-pro-installer/issues/47

also exists for ffraenz/private-composer-installer when using Composer 1. I got the same error message:

> [UnexpectedValueException]                                                                                                                         
> The version constraint of advanced-custom-fields/advanced-custom-fields-pro should be exact (with 3 or 4 digits). Invalid version string "5.10.1"

Updating to Composer 2 does not have this issue.

If using Composer 1, this solution works for philippbaschke, but since ffraenz's isn't acf-pro exclusive, the same solution doesn't look like it applies.
https://github.com/PhilippBaschke/acf-pro-installer/pull/46/commits/13ec41e1026693fb4b6b823a994fe2196064c95e

**Comment by szepeviktor** [comment]
Please issue `PLUGIN_ACF_KEY='ADD_YOUR_KEY_HERE' composer update` with this simple content.

```json
{
    "name": "private-composer-installer/issue-43",
    "description": "https://github.com/ffraenz/private-composer-installer/issues/43",
    "license": "proprietary",
    "require": {
        "advanced-custom-fields/advanced-custom-fields-pro": "^5.10"
    },
    "repositories": [
        {
            "type": "package",
            "package": {
                "name": "advanced-custom-fields/advanced-custom-fields-pro",
                "version": "5.10.1",
                "type": "wordpress-plugin",
                "dist": {
                    "type": "zip",
                    "url": "https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k={%PLUGIN_ACF_KEY}&t={%VERSION}"
                },
                "require": {
                    "composer/installers": "^1.4",
                    "ffraenz/private-composer-installer": "^5.0"
                }
            }
        }
    ]
}
```

It works with Composer v1 (latest) on PHP 7.4.

**Comment by ffraenz** [comment]
I'm not sure where the error message would originate from. I'm not aware of any version validation logic in this plugin similar to [this function](https://github.com/PhilippBaschke/acf-pro-installer/blob/772cec99c6ef8bc67ba6768419014cc60d141b27/src/ACFProInstaller/Plugin.php#L183-L198). As arbitrary packages may be used, any version gets accepted.

**Comment by srsimonson** [comment]
Thanks for the responses. I'll revisit the package updates and make sure I converted from philippbaschke properly.

... Composer 1 updates worked, my error! Powershell error stated something like philippbaschke was still being referenced in cache, so I hadn't fully removed it from my system.
