### ISSUE TITLE
How to setup for a CI build tool?

### ISSUE THREAD

**Issue by jasonmccreary** [ffraenz/private-composer-installer#7]
What is the recommended process for a CI tool such as Travis CI. We are use this package through other WP packages, but since our `.env` is not committed to source, our CI tools are failing to build our project.

Any direction would be appreciate. Thanks!

**Comment by ffraenz** [comment]
In Travis CI you can define environment variables separately in a public and private way. You can for instance define private environment variables in the repository settings in Travis CI without including an `.env` file in the repository. This composer installer checks for env vars first and only if at least one placeholder can't be satisfied the `.env` file is being required.

Find the Travis CI reference about env vars over here:
https://docs.travis-ci.com/user/environment-variables/

I hope this will help.

**Comment by jasonmccreary** [comment]
It does. Thank you for the speedy reply. Keep up the good work!
