### ISSUE TITLE
Update ACF PRO white screen of death

### ISSUE THREAD

**Issue by imstanleyyeo** [ffraenz/private-composer-installer#8]
Thanks @ffraenz for this installer. Works on all my new install site.

Problem arise when I'm trying to upgrade ACP PRO on an existing site moving from [philippbaschke/acf-pro-installer](https://packagist.org/packages/philippbaschke/acf-pro-installer) to yours. Did a composer update by changing the value of `"vlucas/phpdotenv": "^2.0.1"`, to `"vlucas/phpdotenv": "^3.0.0"`, and got a white screen of death.

```
"require": { 
   "php": ">=5.6", "composer/installers": "^1.4",
   "vlucas/phpdotenv": "^3.0.0",
   "johnpbloch/wordpress": "4.9.8",
   "oscarotero/env": "^1.1.0", 
   "roots/wp-password-bcrypt": "1.0.0", 
   "advanced-custom-fields/advanced-custom-fields-pro": "*" 
}
```

Any idea why is it so? Thanks

**Comment by imstanleyyeo** [comment]
Hi @ffraenz,

Were you able to reproduce this?

Thanks

**Comment by imstanleyyeo** [comment]
@ffraenz,

Are you able to reproduce this? Thanks

**Comment by ffraenz** [comment]
Hi @imstanleyyeo, sorry for the late reply.

Which `private-composer-installer` version are you using? In order to use `vlucas/phpdotenv ^3.0.0` you need to set the version of this package to `^2.0` and update your composer dependencies.

If this does not help, please enable PHP error reporting and try to access the error log for this specific event.

**Comment by imstanleyyeo** [comment]
Hello @ffraenz, thanks for taking the time to reply. I'm using your [repo](https://github.com/ffraenz/private-composer-installer) and I did a `composer update` with the  version of the package to `^2.0`. 

Here's the setting used: 
```
{
      "type": "package",
      "package": {
        "name": "advanced-custom-fields/advanced-custom-fields-pro",
        "version": "5.8.1",
        "type": "wordpress-plugin",
        "dist": {
          "type": "zip",
          "url": "https://connect.advancedcustomfields.com/index.php?a=download&p=pro&k={%PLUGIN_ACF_KEY}&t={%version}"
        },
        "require": {
          "composer/installers": "^1.4",
          "ffraenz/private-composer-installer": "^2.0"
        }
      }
    },
```

Then, I got the white screen of death....

**Comment by frisonl** [comment]
Same here, did you find a solution or cause in the end? @imstanleyyeo

**Comment by ffraenz** [comment]
If ACF Pro has been successfully installed using `composer install` this issue is not caused by this composer plugin. Please enable error reporting in your PHP environment and check for any error logs to fix this issue.

**Comment by strarsis** [comment]
Updating `private-composer-installer` from `1.0` to `2.0` using `"ffraenz/private-composer-installer": "^2.0"` fixed the issue for me. Thanks!

**Comment by imstanleyyeo** [comment]
Hello @frisonl 

I realise what caused my issue is because of Wordfence plugin, which added additional rewrite below the basic WP .htaccess rules in my .htaccess file. This causes the WSOD. 

`# BEGIN WordPress

RewriteEngine On
RewriteBase /
RewriteRule ^index\.php$ - [L]
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteRule . /index.php [L]

# END WordPress`
 
Hope this helps somebody and Sorry for wasting everybody's bandwidth!
