### ISSUE TITLE
Don't add the version hash to the URL if the exact version can already be found in the URL.

### ISSUE THREAD

**Issue by alexanderpas** [ffraenz/private-composer-installer#9]
If providing an URL with the version already set in the URL (such as via a Satis repository), since the {%version} variable is not available it will add the version hash to the end of the url.

Example composer repository (created via satis)

```
{
    "packages": {
        "package-name/package-name" : {
            "1.0.0" : {
                "type": "package",
                "name": "package-name/package-name",
                "version": "1.0.0",
                "dist": {
                    "type": "zip",
                    "url": "https://example.com/download?product=package&u={%USER_ID}&key={%SECRET_KEY}&v=1.0.0"
                },
                "require": {
                    "ffraenz/private-composer-installer": "^2.0"
                },
                "uid": 1
            },
            "1.0.1" : {
                "type": "package",
                "name": "package-name/package-name",
                "version": "1.0.1",
                "dist": {
                    "type": "zip",
                    "url": "https://example.com/download?product=package&u={%USER_ID}&key={%SECRET_KEY}&v=1.0.1"
                },
                "require": {
                    "ffraenz/private-composer-installer": "^2.0"
                },
                "uid": 2
            },
            "1.1.0" : {
                "type": "package",
                "name": "package-name/package-name",
                "version": "1.1.0",
                "dist": {
                    "type": "zip",
                    "url": "https://example.com/download?product=package&u={%USER_ID}&key={%SECRET_KEY}&v=1.1.0"
                },
                "require": {
                    "ffraenz/private-composer-installer": "^2.0"
                },
                "uid": 3
            }
        }
    }
}
```

This causes the line in composer.lock to be similar to this:

    "url": "https://example.com/download?product=package&u={%USER_ID}&key={%SECRET_KEY}&v=1.1.0#1.1.0"

After doing a `coposer require` of a different package, the version hash will be doubled at the end of the line.

    "url": "https://example.com/download?product=package&u={%USER_ID}&key={%SECRET_KEY}&v=1.1.0#1.1.0#1.1.0"

**Comment by ffraenz** [comment]
If the exact version is part of the URL, replace it with the `{%version}` placeholder. In this case, no version hash will be appended at the end.

Example:

```
https://example.com/download?product=package&u={%USER_ID}&key={%SECRET_KEY}&v={%version}
```

**Comment by alexanderpas** [comment]
This isn't always possible (such as when the dowload url is being obtained via an API), and doesn't solve the issue of the version number being added multiple times.

    composer require monolog/monolog
    composer remove monolog/monolog
    composer require monolog/monolog
    composer remove monolog/monolog

This set of commands should not add the version number multiple times to an already existing item in the composer.lock file, even if the {%version} token is not found in the original URL.

**Comment by ffraenz** [comment]
Changes have been published in the latest release. Closing this issue.
